"""Assemble the read-only calibration view for the API.

Serves the **held-out** reliability report (walk-forward out-of-sample, generated by
``scripts/run_reliability_export.py`` and persisted as ``models/reliability.json``) so the History
reliability diagram shows honest calibration — never an in-sample recompute (Inviolable Rule 1).
``version`` and ``gate_passed`` come live from the loaded calibrator; the bins/metrics come from
the persisted report. If the report is absent, the gate/version still serialize with ``None``
metrics and empty bins plus a clear ``source`` note — the UI degrades gracefully, nothing invented.
"""

from __future__ import annotations

import json
from pathlib import Path

from ipo.service.views import CalibrationView, ReliabilityBinView


def load_calibration_view(
    report_path: Path | None, *, version: str, gate_passed: bool
) -> CalibrationView:
    """Combine the live calibrator provenance with the persisted held-out reliability report."""
    if report_path is not None and report_path.is_file():
        d = json.loads(report_path.read_text(encoding="utf-8"))
        return CalibrationView(
            version=version,
            gate_passed=gate_passed,
            source=str(d.get("source", "walk-forward out-of-sample")),
            n=int(d["n"]),
            base_rate=float(d["base_rate"]),
            ece=float(d["ece"]),
            brier=float(d["brier"]),
            auc=float(d["auc"]),
            bins=[ReliabilityBinView(**b) for b in d["bins"]],
        )
    return CalibrationView(
        version=version,
        gate_passed=gate_passed,
        source="report not generated",
        n=0,
        base_rate=None,
        ece=None,
        brier=None,
        auc=None,
        bins=[],
    )
